"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import DroneFitApp from "./DroneFitApp";
export type ProjectRecord={id:string;code:string;name:string;stateJson:string;createdAt:string;updatedAt:string};
export default function ProjectPortal(){
 const [projects,setProjects]=useState<ProjectRecord[]>([]),[current,setCurrent]=useState<ProjectRecord|null>(null),[loading,setLoading]=useState(true),[code,setCode]=useState("SX26259"),[name,setName]=useState("Tuiterd Holten"),[query,setQuery]=useState(""),[error,setError]=useState("");
 async function refresh(){setLoading(true);try{const r=await fetch("/api/projects");if(r.ok)setProjects(await r.json());}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 async function create(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,name,state:{projectName:name,site:{lat:52.282539407,lon:6.426162461},siteConfirmed:false,buildings:[]}})});const data=await r.json();if(!r.ok){setError(data.error??"Project kon niet worden gemaakt.");return}setCurrent(data);setProjects(p=>[data,...p]);}
 async function remove(p:ProjectRecord){if(!confirm(p.code+" - "+p.name+" verwijderen?"))return;await fetch("/api/projects/"+p.id,{method:"DELETE"});setProjects(v=>v.filter(x=>x.id!==p.id));}
 const filtered=useMemo(()=>projects.filter(p=>(p.code+" "+p.name).toLowerCase().includes(query.toLowerCase())),[projects,query]);
 if(current)return <DroneFitApp key={current.id} project={current} onBack={()=>{setCurrent(null);refresh()}}/>;
 return <main className="project-home">
  <header className="home-nav"><div className="brand"><span className="brand-mark">D</span><span>DroneFit</span><small>vastgoed camera matching</small></div><span className="home-secure">Prive projectomgeving</span></header>
  <section className="home-hero"><div><span className="eyebrow">VAN LOCATIE NAAR PERFECTE INPASSING</span><h1>Een dronebeeld dat straks al gebouwd lijkt.</h1><p>Leg de locatie vast, lijn de situatietekening uit en stuur de cameramatch met een paar klikken naar Blender.</p><div className="flow-pills"><span>1 Adres & kaart</span><span>2 Situatie-PDF</span><span>3 DJI-foto</span><span>4 Woningen</span><span>5 Render</span></div></div><div className="hero-preview"><div className="preview-sky"/><div className="preview-site"><i/><i/><i/><i/></div><div className="preview-card"><b>SX26259 - Tuiterd Holten</b><span>Camera en 4 woningblokken uitgelijnd</span></div></div></section>
  <section className="project-grid"><form className="new-project-card" onSubmit={create}><span className="card-kicker">NIEUW PROJECT</span><h2>Start een nieuwe inpassing</h2><p>Gebruik de SX-code zoals die ook in jullie mappen staat.</p><label>SX-projectnummer<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="SX26259" pattern="SX[0-9]{4,}" required/></label><label>Locatie / projectnaam<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tuiterd Holten" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" type="submit">Nieuw project maken</button></form>
   <div className="existing-projects"><div className="projects-head"><div><span className="card-kicker">BESTAAND PROJECT</span><h2>Ga verder waar je was</h2></div><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoek op SX of locatie..."/></div><div className="project-list">{loading?<div className="empty-projects">Projecten laden...</div>:filtered.length===0?<div className="empty-projects"><b>Nog geen projecten</b><span>Maak links je eerste SX-project aan.</span></div>:filtered.map(p=>{let s:any={};try{s=JSON.parse(p.stateJson||"{}")}catch{}return <div className="project-item" key={p.id}><button className="project-open" onClick={()=>setCurrent(p)}><span className="project-code">{p.code}</span><span><b>{p.name}</b><small>{s.drone?"Dronefoto gekoppeld":"Locatie voorbereiden"} · {(s.buildings?.length??0)} woningblokken</small></span><time>{new Date(p.updatedAt).toLocaleDateString("nl-NL")}</time></button><button className="delete-project" onClick={()=>remove(p)} aria-label="Verwijder project">x</button></div>})}</div></div>
  </section>
 </main>;
}